language: go

go:
  - 1.x

install:
  # Add Godeps dependencies to GOPATH and PATH
  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"
  # Install dependencies
  - . $HOME/.nvm/nvm.sh
  - nvm install
  - make install
